### ISSUE TITLE
New issues

### ISSUE THREAD

**Issue by ismayito** [AbuTalha3/Todo-list#5]

**Comment by ismayito** [comment]
Hi Abu Talha:
Thanks for the work done so far, but you can have the functionalities of different parts modularized such as the remove function, the edit function and others such that they can be easily read and become clean code for future improvement and collaboration

**Comment by Pi1998** [comment]
#Review
- Nice design implementation
- Fulfiled functionalities as required
Great work.

It would be better to add some documentation for better understanding, maintainability, and reusability.

**Comment by lucy-sees** [comment]
Your project looks neat!  

## To Highlight
- Descriptive commit messages ✔️  
- Good overall design ✔️ 

Cheers and Happy coding!👏👏👏
